### ISSUE TITLE
clash 谷歌插件  clash查看端口  clash文件配置

### ISSUE THREAD

**Issue by clashvpn18** [clashvpn18/clashvpn#3]
推荐榜单1、爱连VPN
邀请好友注册充值返利高达40-50%
永久官网注册登陆网址：（打不开请点击下面导航）https://www.iovevpn.com/
永久导航：（最新网址进导航页面查找）https://www.ailianvpn.com/
爱连VPN手机下载（支持安卓-Winodws-MAC-苹果ios）https://www.ivpn.im
相比直连机场更加推荐购买中转机场。中转机场机器便宜一般更加带宽大，公网主要问题是出口偶尔会绕路导致网络波动影响。专线主要是不过墙延迟低，网络波动小，专线机场日常使用体验会更丝滑更舒服。机场比的是钞能力，速度要看机场的总带宽大小。稳定要看机场的资源质量，主要是看机场主的上游的线路质量，解锁看的是机场主的落地/解锁商是否优秀。机场带宽大和稳定性最重要。

### Clash 谷歌插件

**Clash 谷歌插件**（也称为 Clash 插件）通常指的是为谷歌浏览器（Chrome）或其他基于 Chromium 的浏览器提供的扩展，用于与 Clash 配置进行集成。以下是如何安装和使用这些插件：

#### **1. 安装 Clash 插件**

1. **访问 Chrome 网上应用店**：
   - 打开 Google Chrome 浏览器，访问 [Chrome 网上应用店](https://chrome.google.com/webstore/category/extensions)。

2. **搜索 Clash 插件**：
   - 在搜索框中输入 `Clash` 或 `Clash for Chrome`。可能会找到多个与 Clash 相关的插件。

3. **选择并安装插件**：
   - 选择适合的 Clash 插件（例如 `Clash for Chrome`）并点击“添加到 Chrome”按钮，按照提示完成安装。

4. **配置插件**：
   - 安装后，点击浏览器工具栏中的插件图标，输入或导入 Clash 的配置链接。确保插件已连接到 Clash 代理服务。

#### **2. 使用 Clash 插件**

1. **启用插件**：
   - 确保插件已启用并连接到 Clash 代理服务。

2. **配置代理规则**：
   - 在插件设置中，可以配置代理规则、选择节点等。

3. **测试代理功能**：
   - 访问被屏蔽或受限的网站，确保插件通过 Clash 代理正常工作。

### Clash 查看端口

**Clash 查看端口** 通常是指查看 Clash 运行时使用的端口，以便进行配置或排除故障。以下是一些方法来查看 Clash 的端口设置：

#### **1. 查找 Clash 配置文件**

1. **打开配置文件**：
   - 找到 Clash 的配置文件，通常是 `config.yaml` 或类似的文件。

2. **查看端口设置**：
   - 查找 `port` 配置项，通常在 `proxy` 或 `dns` 配置部分中。例如：
     ```yaml
     port: 7890
     socks-port: 7891
     redir-port: 7892
     ```
   - 上述配置指定了 Clash 的 HTTP 代理端口、SOCKS 代理端口和透明代理端口。

#### **2. 使用命令行工具**

1. **在终端中查看端口**：
   - 打开终端或命令提示符，使用命令 `netstat` 或 `ss` 来查看端口占用情况。
     ```bash
     netstat -tuln | grep 7890
     ```
   - 或者使用 `ss` 命令：
     ```bash
     ss -tuln | grep 7890
     ```

2. **检查 Clash 进程**：
   - 通过 `ps` 命令检查 Clash 进程，并确认它正在监听正确的端口。
     ```bash
     ps aux | grep clash
     ```

### Clash 文件配置

**Clash 文件配置** 是指设置 Clash 代理的配置文件，通常使用 YAML 格式。以下是如何配置 Clash 的文件，以及常见的配置项：

#### **1. 配置文件结构**

Clash 的配置文件通常包括以下几个部分：

1. **代理节点**：
   ```yaml
   proxies:
     - name: "ExampleProxy"
       type: ss
       server: example.com
       port: 8388
       cipher: "aes-256-gcm"
       password: "password"
   ```

2. **规则**：
   ```yaml
   rules:
     - DOMAIN-SUFFIX,example.com,ExampleProxy
     - IP-CIDR,192.168.1.0/24,DIRECT
     - MATCH,ExampleProxy
   ```

3. **DNS**：
   ```yaml
   dns:
     enable: true
     servers:
       - 8.8.8.8
       - 1.1.1.1
   ```

4. **端口设置**：
   ```yaml
   port: 7890
   socks-port: 7891
   redir-port: 7892
   ```

5. **日志**：
   ```yaml
   log-level: info
   ```

#### **2. 编辑配置文件**

1. **使用文本编辑器**：
   - 打开配置文件，使用文本编辑器（如 Notepad++、VS Code、Sublime Text）进行编辑。

2. **修改和保存**：
   - 根据需要修改配置项，如代理节点、规则、端口等。保存文件并重新启动 Clash 以应用更改。

#### **3. 配置文件示例**

这是一个简单的配置文件示例：

```yaml
proxies:
  - name: "Proxy1"
    type: http
    server: proxy1.example.com
    port: 8080
    username: user
    password: pass

rules:
  - DOMAIN-KEYWORD,google,Proxy1
  - MATCH,DIRECT

dns:
  enable: true
  servers:
    - 8.8.8.8
    - 1.1.1.1

port: 7890
socks-port: 7891
redir-port: 7892
log-level: info
```
